<?//$GLOBALS["arrPopFilterProp"]=array("PROPERTY_HIT_VALUE" => array("Хиты продаж"));?>
<hr class="long"/>
<div class="popular_products_wrapp">
	<?$APPLICATION->IncludeComponent(
		"bitrix:catalog.top", 
		"products_slider_v2", 
		array(
			"IBLOCK_TYPE" => "aspro_optimus_catalog",
			"IBLOCK_ID" => \Bitrix\Main\Config\Option::get("aspro.optimus", "CATALOG_IBLOCK_ID", '87'),
			"ELEMENT_SORT_FIELD" => "sort",
			"ELEMENT_SORT_ORDER" => "asc",
			"ELEMENT_COUNT" => ($arParams["ELEMENTS_PAGE_COUNT"] ? $arParams["ELEMENTS_PAGE_COUNT"] : 20),
			"LINE_ELEMENT_COUNT" => "",
			"PROPERTY_CODE" => array(
				0 => "",
				1 => "",
			),
			"OFFERS_LIMIT" => "10",
			"SECTION_URL" => "",
			"DETAIL_URL" => "",
			"BASKET_URL" => SITE_DIR."basket/",
			"ACTION_VARIABLE" => "action",
			"PRODUCT_ID_VARIABLE" => "id",
			"PRODUCT_QUANTITY_VARIABLE" => "quantity",
			"PRODUCT_PROPS_VARIABLE" => "prop",
			"SECTION_ID_VARIABLE" => "SECTION_ID",
			"CACHE_TYPE" => "A",
			"CACHE_TIME" => "3600000",
			"CACHE_GROUPS" => "N",
			"DISPLAY_COMPARE" => "Y",
			"PRICE_CODE" => array(
				0 => "для сайта - не использовать для клиентов!!!",
			),
			"USE_PRICE_COUNT" => "N",
			"SHOW_PRICE_COUNT" => "1",
			"PRICE_VAT_INCLUDE" => "Y",
			"PRODUCT_PROPERTIES" => array(
			),
			"CONVERT_CURRENCY" => "N",
			"FILTER_NAME" => "arrPopFilterProp",
			"SHOW_BUY_BUTTONS" => "Y",
			"USE_PRODUCT_QUANTITY" => "N",
			"INIT_SLIDER" => "Y",
			"COMPONENT_TEMPLATE" => "products_slider_v2",
			"ELEMENT_SORT_FIELD2" => "id",
			"ELEMENT_SORT_ORDER2" => "desc",
			"HIDE_NOT_AVAILABLE" => "Y",
			"OFFERS_FIELD_CODE" => array(
				0 => "ID",
				1 => "NAME",
				2 => "",
			),
			"OFFERS_PROPERTY_CODE" => array(
				0 => "",
				1 => "",
			),
			"OFFERS_SORT_FIELD" => "sort",
			"OFFERS_SORT_ORDER" => "asc",
			"OFFERS_SORT_FIELD2" => "id",
			"OFFERS_SORT_ORDER2" => "desc",
			"SEF_MODE" => "N",
			"CACHE_FILTER" => "Y",
			"SHOW_MEASURE" => "Y",
			"MESS_BTN_BUY" => "В корзину",
			"ADD_PROPERTIES_TO_BASKET" => "Y",
			"PARTIAL_PRODUCT_PROPERTIES" => "N",
			"OFFERS_CART_PROPERTIES" => array(
			),
			"COMPARE_PATH" => "",
			"SHOW_DISCOUNT_PERCENT" => "Y",
			"SHOW_OLD_PRICE" => "Y",
			"SHOW_RATING" => "N",
			"DISPLAY_WISH_BUTTONS" => \Bitrix\Main\Config\Option::get('aspro.optimus', 'SHOW_DELAY', 'Y'),
			"SHOW_TITLE" => "Y",
			"TITLE" => "Популярные товары",
			"FOOTER_BUTTON_STATIC" => "Y",
		),
		false, array("HIDE_ICONS"=>"Y")
	);?>
</div>